FEATURE: BEND-19 Photoid endpoint
Worksut/account-microservice-api pull request #15
Opened 2022-01-17 07:33 UTC by octapf

2022-01-17 09:33 UTC, whitehatdevv commented
@octapf check the new name I have just put, it's recommended to set the right name

2022-01-17 13:17 UTC, whitehatdevv requested changes

2022-01-17 13:17 UTC, whitehatdevv commented on src/http/actions/Account.ts
>  }
This action is not the appropriated one to get the photo by a current ID. here you are looking for an account but not for the photo indicated by the Id, please don't copy and paste the code I made before.

2022-01-19 09:36 UTC, octapf commented on src/http/actions/Account.ts
>  }
@whitehatdevv I have changed the action to get the photoId correctly

2022-01-20 07:05 UTC, whitehatdevv requested changes

2022-01-20 07:05 UTC, whitehatdevv commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
This route should be `/account/:accountId/photo/:photoId`. Please change it

2022-01-20 07:08 UTC, octapf commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
@manu En notion está distinto
![image](https://user-images.githubusercontent.com/62032399/150290175-552ddbd5-f4ac-4541-ae98-7e57be6ac3f3.png)

2022-01-20 07:08 UTC, whitehatdevv commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
Then it's a mistake on notion, please change the route on your code and notion too

2022-01-20 07:09 UTC, octapf commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
También el BEND-14 tiene profile/photo

2022-01-20 07:13 UTC, whitehatdevv commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
Then change too, it was my fault, I'm sorry

2022-01-20 08:53 UTC, octapf commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
Ok no problem!

2022-01-20 10:03 UTC, octapf commented on src/http/common/Base/static/Base.AccountEndpoints.ts
> +  PhotoId = '/account/:accountId/profile/photo/:photoId',
Already fixed. Will appear on next commit.

2022-01-21 11:28 UTC, merged