Feature/BEND-08-me-endpoint
Worksut/account-microservice-api pull request #17
Opened 2022-01-17 15:11 UTC by Kehomaxd

2022-01-18 11:24 UTC, Kehomaxd commented
@whitehatdevv  what happend here? i dont understand what is wrong

2022-01-20 07:08 UTC, whitehatdevv commented
@Kehomaxd you have conflicts, try to fix it pls

2022-01-20 13:19 UTC, Kehomaxd commented
@whitehatdevv  done

2022-01-21 06:44 UTC, whitehatdevv requested changes
You have to: 
- Remove all the unused whitespaces.
- Document all the interfaces (DOM objects) -> You have forgotten the author github name
- Fix all this errors.
- Format the code before pushing, select all the code, use your right click and look for an option called format document

2022-01-21 06:44 UTC, whitehatdevv commented on src/http/actions/Account.ts
> +      const dom: Me = {
This object can be created using a mapper. 
```js
f(null, <Me>dto);
```

Please remove all the object transformation.

2022-01-21 06:44 UTC, whitehatdevv commented on src/models/domain/domain.education.ts
> +}
Please keep on mind format the code before make a push, it's a mandatory

2022-01-21 06:44 UTC, whitehatdevv commented on src/models/domain/domain.me.ts
> +
Remove this white space.

2022-01-21 13:08 UTC, merged